[package]
name = "echor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0"
assert_cmd = "2.0.17"
predicates = "3.0.4"
pretty_assertions = "1.4.1"
